src/Web/WebSite/Controllers/ChannelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Domain.User.Model;
using Domain.User.Repository;
using Infrastructure.Resilience.Http;
using WebSite.Extensions;
using WebSite.Hubs;
using WebSite.Infrastructure.Repository;
using WebSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using RestSharp;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
// ReSharper disable ForCanBeConvertedToForeach

namespace WebSite.Controllers
{
    public class ChannelController : Controller
    {
        private readonly IMemoryCache _cache;
        private readonly IUserRepository _userRepository;
        private readonly ResilientHttpInvoker _httpInvoker;
        private readonly IHubContext<ChannelHub> _hubContext;

        private readonly IHubContext<ChannelHub> _channelHubContext;

        private readonly IHubContext<FeedHub> _feedHubContext;
        private readonly IReportingRepository _reportingRepository;
        private readonly IOptions<ChannelApiSettings> _ChannelApiSettings;

        private readonly IOptions<FeedApiSettings> _FeedApiSettings;
        public ChannelController(IUserRepository userRepository,
            IMemoryCache cache,
            ResilientHttpInvoker httpInvoker,
            IOptions<ChannelApiSettings> ChannelApiSettings,
            IOptions<FeedApiSettings> FeedApiSettings,
            IHubContext<ChannelHub> channelHubContext,
            IHubContext<FeedHub> feedHubContext,
            IReportingRepository reportingRepository)
        {
            _userRepository = userRepository;
            _cache = cache;
            _httpInvoker = httpInvoker;
            _ChannelApiSettings = ChannelApiSettings;
            _FeedApiSettings = FeedApiSettings;
            _channelHubContext = channelHubContext;
            _feedHubContext = feedHubContext;
            _reportingRepository = reportingRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateChannelAsync(ChannelRequestModel channelRequest)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState.AllErrors());

            await _channelHubContext.Clients.All.SendAsync("NotifyChannel", "Created");

            await CreateChannel(channelRequest);

            //await CreateFeed();
            /*await _hubContext.Clients.All.SendAsync("NotifyChannel", "Accepted");

            await AcceptOrStartChannel(_ChannelApiSettings.Value.StartUrl , int.NewGuid());
            await _hubContext.Clients.All.SendAsync("NotifyChannel", "Started");

            await _hubContext.Clients.All.SendAsync("UpdateChannel", "123");

            await _hubContext.Clients.All.SendAsync("NotifyChannel", "Finished");*/

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> MediaOfChannelAsync()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState.AllErrors());

            await _channelHubContext.Clients.All.SendAsync("NotifyChannel", "Created");

            //await CreateChannel();

            //await CreateFeed();
            /*await _hubContext.Clients.All.SendAsync("NotifyChannel", "Accepted");

            await AcceptOrStartChannel(_ChannelApiSettings.Value.StartUrl , int.NewGuid());
            await _hubContext.Clients.All.SendAsync("NotifyChannel", "Started");

            await _hubContext.Clients.All.SendAsync("UpdateChannel", "123");

            await _hubContext.Clients.All.SendAsync("NotifyChannel", "Finished");*/

            return Ok();
        }

        public async Task<IActionResult> ChannelsByUser()
        {
            var users = await GetUsers();
            var usersModel = users.Select(x => new UserModel
            {
                Id = x.Id,
                Email = x.Email,
                Name = x.Name,
                NumberPhone = x.NumberPhone
            });

            return View(usersModel.ToList());
        }

        public async Task<IActionResult> ChannelById(int id)
        {
            try
            {
                var Channel = await _reportingRepository.GetChannelAsync(id);
                return View("ChannelDetails", Channel);
            }
            finally
            {
                _reportingRepository.Dispose();
            }
        }

        private async Task<IList<User>> GetUsers()
        {
            var users = await GetDataFromCache("users", () => _userRepository.GetUsersAsync());
            return users;
        }

        private async Task<T> GetDataFromCache<T>(string cacheKey, Func<Task<T>> action)
        {
            if (!_cache.TryGetValue(cacheKey, out T result))
            {
                result = await action();

                var cacheEntryOptions = new MemoryCacheEntryOptions()
                    .SetSlidingExpiration(TimeSpan.FromMinutes(5));

                _cache.Set(cacheKey, result, cacheEntryOptions);
            }

            return result;
        }

        private async Task<int> CreateChannel(ChannelRequestModel channelRequest)
        {
            var createRequestRresponse = await _httpInvoker.InvokeAsync(async () =>
            {
                var client = new RestClient(_ChannelApiSettings.Value.BaseUrl);
                var request = new RestRequest(_ChannelApiSettings.Value.CreateUrl, Method.POST);
                request.AddJsonBody(new
                {
                    ChannelId = 1,
                    Name = channelRequest.Name,
                    ImageUrl = channelRequest.ImageUrl,
                    IsActive = true,
                    IsDeleted = false
                });
                //throw new InvalidOperationException("There was an error with Channel service");
                return await client.ExecuteTaskAsync(request);
            });

            return JsonConvert.DeserializeObject<int>(createRequestRresponse.Content);
        }

        private async Task<int> MediaOfChannel()
        {
            var createRequestRresponse = await _httpInvoker.InvokeAsync(async () =>
            {
                var client = new RestClient(_ChannelApiSettings.Value.BaseUrl);
                var request = new RestRequest(_ChannelApiSettings.Value.CreateUrl, Method.POST);
                request.AddJsonBody(new
                {
                    ChannelId = 1,
                    Name = "123",
                    ImageUrl = "123",
                    IsActive = true,
                    IsDeleted = false
                });
                //throw new InvalidOperationException("There was an error with Channel service");
                return await client.ExecuteTaskAsync(request);
            });

            return JsonConvert.DeserializeObject<int>(createRequestRresponse.Content);
        }

    }
}

src/Web/WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebSite</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebSite</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Channel" asp-action="Index">Create channel</a></li>
                    <li><a asp-area="" asp-controller="Feed" asp-action="Index">Create feed</a></li>
                    <li><a asp-area="" asp-controller="Feed" asp-action="Feeds">All feeds</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebSite</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/lodash/lodash.js"></script>
        <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/lib/lodash/dist/lodash.min.js"></script>
        <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>